version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: people
    ports:
      - 3306:3306

  app:
    build: 
      context: .
      target: app
    depends_on: 
      - db
    ports:
      - 3000:3000

  nginx:
    build: 
      context: .
      target: nginx
    depends_on: 
      app:
        condition: service_started
    ports:
      - 8080:8080